export const minutes = document.getElementById('minutes')
export const seconds = document.getElementById('seconds')
export const controls = document.getElementById('controls')
export const musicMode = document.getElementById('music-mode')
export const firstMusic = document.getElementById('forest')
export const secondMusic = document.getElementById('rain')
export const thirdMusic = document.getElementById('coffe-shop')
export const fourthMusic = document.getElementById('fireplace')